### ISSUE TITLE
Error in Curve Edit Menu

### ISSUE THREAD

**Issue by Voxyn** [art103/ar-t6#10]
When enabling more than three points to edit, the firmware does not navigate in model menu. When enabling 5 editable points the firmware fails to load completely

**Comment by michkrom** [comment]
>> When enabling more than three points to edit, the firmware does not
navigate in model menu.

what do you mean by "three points..." - the curve points? and what do you
mean by "enabling" - build-time change ?

>> ...the firmware fails to load completely...
This sounds as if the code got too big -  there is no erro in the build to
warn you about it.  I had problems building on Linux with stock 4.8 gcc (I
think it was picking a big libc and building the code corrupted). The gcc
4.9.3 windows/linux works fine. Also try to change to -Os in Project
Preferences/Compiler settings to test if it gets better.

If that's not it then please explain more what you mean and do.



On Mon, Mar 2, 2015 at 1:11 PM, Voxyn <notifications@github.com> wrote:

> When enabling more than three points to edit, the firmware does not
> navigate in model menu. When enabling 5 editable points the firmware fails
> to load completely
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/art103/ar-t6/issues/10>.
>



-- 
Michal, Iza, Kai & Nell

**Comment by Voxyn** [comment]
I mean the curve points. With enabling I mean uncommenting the lines in the code.
Will work on the compiler settings tomorrow. My gcc is 4.9.3

**Comment by michkrom** [comment]
Looks like github messed us up with CR/LF . The files are in CR/LF while looks like you got it converted to CR (likely Eclipse messed up as it enforces NLs per workspace rather the retaining original per file...it really turns me into MS lover :-( ).  
Looks like your checking was based on older version and way behind main. So please "git reset/git pull" (re-get all from github) as a lot of changes got clobbered. Had to manually recover from history. Also, the bug in sub pages is still therr (must have lost your change) : pressing OK immediatly moves to the sub page. Pressing MENU work though right.

**Comment by michkrom** [comment]
Also, I have tried to streamline the curve editor code but left it very unfinished. This should give you some ideas how to implement it, I hope.

**Comment by Voxyn** [comment]
Ok, sorry for the trouble. First time project with github. Just used to SVN and committing

**Comment by michkrom** [comment]
No problem, quoting Forest Gump "s...t happens"!. It's more of the
github+Eclipse combo that is taking us (me too) for a ride.

Just please make sure your editor (Eclipse? or?) is set to Window CR/LF for
now.

We need to study this guide more:
https://help.github.com/articles/dealing-with-line-endings/

And I think we may convert everything to Unix style following this:
http://stackoverflow.com/questions/1886185/eclipse-and-windows-newlines



On Tue, Mar 3, 2015 at 11:36 AM, Voxyn <notifications@github.com> wrote:

> Ok, sorry for the trouble. First time project with github. Just used to
> SVN and committing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/art103/ar-t6/issues/10#issuecomment-77017708>.
>



-- 
Michal, Iza, Kai & Nell

**Comment by michkrom** [comment]
completed curve drawing and editing
