### ISSUE TITLE
fix the newline handling in github/code

### ISSUE THREAD

**Issue by michkrom** [art103/ar-t6#11]
The github here is not set up to autocorrect newlines. Need to create project specific .gitattributes file to make it correct newlines. What should we pick? Originally it is CRLF ....so CR or CRLF? In my private fork i have set it up to CR (unix) style and it works fine on Linux (ya!). Need to verify this on Windows and then pull it to main.

**Comment by art103** [comment]
+1 for CR (Unix)

**Comment by michkrom** [comment]
OK. LF it is. Pushed in.
