### ISSUE TITLE
Add a makefile for compiling the code in bare linux environment

### ISSUE THREAD

**Issue by digitalentity** [art103/ar-t6#13]
Most developers have a *nix environment with GNU MAKE building tool. Migrating to a bare MAKEFILE build would attract more developers to this project (me included). I myself have a FlySky TF-T6 and am willing to use and improve this firmware, but I don't use neither Eclipe nor CodeSourcery ARM toolchain. Just a simple MAKE + GNU GCC.

**Comment by michkrom** [comment]
You got it! Builds now from linux cli. All you need is gnu arb eabi toolchain and build essentials (make at minimum).

**Comment by digitalentity** [comment]
@michkrom, thanks!
