### ISSUE TITLE
Add ability to reset EEPROM contents

### ISSUE THREAD

**Issue by digitalentity** [art103/ar-t6#14]
This will allow user to do a "factory reset" and start from scratch.

**Comment by michkrom** [comment]
Ok, I will add a "Factory Reset" popup to the "Radio settings". This would all models as well. Note, there is a "Model Preset" in model selection page (long-press MENU - standard for popups).

**Comment by michkrom** [comment]
Added "factory" preset popup in "radio settings page 1" - long-hold menu. This perhaps now need a "better" factory defaults...
