### ISSUE TITLE
Flashing the firmware

### ISSUE THREAD

**Issue by mkschreder** [art103/ar-t6#5]
Can you outline the way you are flashing firmware to the tx? Have you soldered a wire to the boot1 pin that you pull high or are you using another method?

**Comment by mkschreder** [comment]
Ok. I was able to put it into boot mode by pulling boot0 high. It works. My board has 128k flash though. The TX can be flashed using the serial port on the back. One does need to pull the boot0 pin high before powering on the board though in order to put it into upgrade mode.

**Comment by michkrom** [comment]
Very interesting... I thought the original fw had build in flasher as there is a "fw upgrade" menu option... do you mean you have version of fst6 with MCU with 128k flash?

I use swd to flash
http://minkbot.blogspot.com/2014/10/fs-t6-and-swd-hack.html?m=1

Also check openers forums for art6.

**Comment by michkrom** [comment]
openrc that is...

**Comment by michkrom** [comment]
Ahhh...the build in stm32 boot loader can be activated from main fw after boot. I bet this is what orig fw does...this would be handy later for normal user to upgrade.

**Comment by mkschreder** [comment]
Yes my board is identified as having 128k by stm32flash utility. I dumped the original fw and it was 128k file as well. 

All st chips I've used so far had a builtin bootloader that can boot from uart1 and can be activated by pulling boot0 high and boot1 low. Problem with the fst6 board is it doesn't have a jumper connected to boot0. So requires a little mod. :-)

Also my board has a capacitor across the boot0 pull down resistor. This cap was missing on your schematic..

**Comment by art103** [comment]
Hi Martin,

Good to see someone else helping push things forwards!
We have been using the 20-pin header and SWD connections to flash the 
board.
This also allows gdb debugging.
The STM32 discovery boards are pretty cheap and have an external SWD 
port that is good for this purpose.

The chip on mine is definitely 64KiB - confirmed by the part number and 
the tools. I'm guessing the price came down on the 128KiB version.

Regarding the schematic - I am sure there are other bits missing too, it 
was a case of follow the tracks and use a multimeter until I worked out 
the bits I needed.

Longer term the back connector and software initiated update would be a 
great feature - especially if it is compatible with the FS-T6 updater 
too (i.e. allows people to go both ways).

I did experiment with the serial loader in the original firmware for 
about 20 mins but was unsuccessful.
What utility do you use to flash via serial?

**Comment by mkschreder** [comment]
I'm using stm32flash that is part of my libk repo: https://github.com/mkschreder/martink/tree/master/scripts/stm32flash 

I wrote a log on how to get it all working here: http://martinschroder.se/hacking-flysky-fs-t6-transmitter/

Also, the crystal on my board is 12Mhz. At first I had problem getting timings to work, but that's because I was used to 8mhz standard crystals on other stm32 boards. This one is 12mhz so when compiling CMSIS, HSE_VALUE needs to be adjusted accordingly..

**Comment by mkschreder** [comment]
https://www.youtube.com/watch?v=JD_hfML0R8c

**Comment by art103** [comment]
Hi Martin,

That's great.
Have you kept the DMA and IRQ architecture for sampling the sticks?
This was a major design element and allows the CPU to be free to do 
other things (i.e. drive the UI).

Kind regards,
Richard.

**Comment by mkschreder** [comment]
DMA ADC implementation: https://github.com/mkschreder/martink/blob/master/arch/arm/stm32/adc.c

**Comment by natanke** [comment]
Hi
I watch your project a few months and would like to help if I can be helpful. But I'm not a programmer.
I like to do modifications. Now I have a FS-T6 with 8 channel radio module Frsky DHT and receiver V8FR-II, I used this post http://www.rcgroups.com/forums/showpost.php?p=27565997&postcount=390. To select the radio module I use the toggle switch.
I also replaced the VRA by 6 position switch to change flight modes and add 6 leds to indicate it. My transmitter have 64K eeprom.
![collage1](https://cloud.githubusercontent.com/assets/11172794/6500045/837c874a-c32f-11e4-9c2b-8c3e39fd18e6.jpg)
I would like to help test your software, but I could not find information on how to compile the sources to the bin file. Could you provide this information, as it did in the project cleanflight - https://github.com/cleanflight/cleanflight/blob/master/docs/development/Building%20in%20Windows.md I think it would help attract people to the project.
Sorry for my english, with best regards, Roman.

**Comment by michkrom** [comment]
Roman,

Sick mods dude! Cool.

Compiling the code is one problem, programming it into TX is another.

At the moment we use SW debugger cable. At some point we'd adapt STM's
built-in update through serial connection available on S-Video plug on the
back.

Here are some related links:
http://openrcforums.com/forum/viewforum.php?f=124 <http://openrcforums.com/>
http://minkbot.blogspot.com/

Michal



On Wed, Mar 4, 2015 at 10:07 PM, Roman <notifications@github.com> wrote:

> Hi
> I watch your project a few months and would like to help if I can be
> helpful. But I'm not a programmer.
> I like to do modifications. Now I have a FS-T6 with 8 channel radio module
> Frsky DHT and receiver V8FR-II, I used this post
> http://www.rcgroups.com/forums/showpost.php?p=27565997&postcount=390. To
> select the radio module I use the toggle switch.
> I also replaced the VRA by 6 position switch to change flight modes and
> add 6 leds to indicate it. My transmitter have 64K eeprom.
> [image: collage1]
> <https://cloud.githubusercontent.com/assets/11172794/6500045/837c874a-c32f-11e4-9c2b-8c3e39fd18e6.jpg>
> I would like to help test your software, but I could not find information
> on how to compile the sources to the bin file. Could you provide this
> information, as it did in the project cleanflight -
> https://github.com/cleanflight/cleanflight/blob/master/docs/development/Building%20in%20Windows.md
> I think it would help attract people to the project.
> Sorry for my english, with best regards, Roman.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/art103/ar-t6/issues/5#issuecomment-77312100>.
>



-- 
Michal, Iza, Kai & Nell

**Comment by natanke** [comment]
@michkrom programming transmitter is not a problem, I have experience of the programming microcontroller stm32 by using usb to uart adapter. I also ordered ST-Link v2 debugger.

**Comment by mkschreder** [comment]
Yes usb uart and stm32flash utility is by far the most foolproof way to
program them. Look up stm32flash. You basically need a cheap ft232 usb to
serial adapter from ebay and the rest is free.

**Comment by michkrom** [comment]
Anybody claims ownership of this issue? I would be willing to work on puting stm32flash util as a preferred way to upgrade FW. This would consist of putting an ability to boot into the stm32 build-in bootloader from ar-t6 FW and verifying that stm32flash works with it.

**Comment by michkrom** [comment]
Implemented entering stm bootloader from System/Version/MENU (pres&hold SELect). Verified that stm32flash util works for both original fw and ar-t6 (both alowed for programming the other fw), Note that now we are able to upgrade FS-T6 to both ar-t6 custom FW and reverting back to original - both without opening the case.

Short writeup here:
http://minkbot.blogspot.com/2015/03/fs-t6-firmware-upgrade.html

**Comment by Voxyn** [comment]
When I flash my device from Windows (Eclipse or STM Linker), the remote will not boot unless the USB adapter is connected to it. 
Any ideas on how to fix it? I want to test some of my changes with my quadcopter

**Comment by natanke** [comment]
@Voxyn today I compiled and flashed ar-t6 то my Tx via fs-ct6b usb cable - http://www.ebay.com/itm/231501106142 and I use STM32 Flash Loader Demonstrator - http://www.st.com/web/en/catalog/tools/FM147/CL1794/SC961/SS1533/PF257525
You must to use only 3 pin of your usb to uart adapter - RX, TX and GND like here http://minkbot.blogspot.ru/2015/03/fs-t6-firmware-upgrade.html

**Comment by michkrom** [comment]
>> When I flash my device from Windows (Eclipse or STM Linker), the remote
will not boot unless the USB adapter is connected to it.
By "flash" do you mean using SWD connection and not serial? With SWD I
experience the following when I cycle power on Tx when SWD is connected the
Tx stays in reset. Disconnecting SWD cable makes it boot.

Did you try to step through initialization (as I suspect the eeprom/i2c
code is the culprit but who knows...)? It's complicated...



On Tue, Mar 10, 2015 at 10:24 AM, Voxyn <notifications@github.com> wrote:

> When I flash my device from Windows (Eclipse or STM Linker), the remote
> will not boot unless the USB adapter is connected to it.
> Any ideas on how to fix it? I want to test some of my changes with my
> quadcopter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/art103/ar-t6/issues/5#issuecomment-78103259>.
>



-- 
Michal, Iza, Kai & Nell

**Comment by Voxyn** [comment]
I flash with SWD using the STM32 linker tool from within windows. 
The device boots now when disconnecting the SWD connection but still the error with the eeprom persists:
When I enter the menu or hit one of the trim toggles, the devices freezes and I need to power down and up. 
I flashed the original firmware and it works without a problem, so no hardware error, I suspect

**Comment by Voxyn** [comment]
Ok, I fixed the error by switching to another version of the compiler. After re-compiling all is running fine :)

**Comment by michkrom** [comment]
Could you write what version were you using and what fixed it?

On Thu, Mar 12, 2015 at 1:45 PM, Voxyn <notifications@github.com> wrote:

> Ok, I fixed the error by switching to another version of the compiler.
> After re-compiling all is running fine :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/art103/ar-t6/issues/5#issuecomment-78608783>.
>



-- 
Michal, Iza, Kai & Nell

**Comment by Voxyn** [comment]
I used the gcc-arm-none-eabi-4_9-2014q4-20141203-win32 compiler version before. After switching to 4.9.2-eabi using the prebuilt toolchain for windows it worked. Got it from this page: http://gnutoolchains.com/arm-eabi/

**Comment by digitalentity** [comment]
I've noticed that sometimes gcc-arm-none-eabi-4.9 provides buggy code for STM32F103 processor. I don't know exact conditions to reproduce the bug, but currently I stick with gcc 4.8 toolchain - provides working code for me.

**Comment by michkrom** [comment]
I am using the 4.9.2q4 from https://launchpad.net/gcc-arm-embedded/+download under windows and it works fine so far 4me...I have observed under linux that 4.8 did not work for me (the stock arm-none-eabi in ubuntu 14.04) but again the above 4.9.2 did. Not fun. :-(

**Comment by michkrom** [comment]
Voxyn,

The toolchain you're using uses arm-eabi-' instead of 'arm-none-eabi-' - so
did you have to change the project's toolchain definition or did you create
'links' to avoid messing with project's settings? Seems that these
toolchains are equivalent (afaik, the 'none' stands for 'none-operating
system' as there are gcc-linux-elf etc toolchains.).

Since different versions work for different people, there seem to be a
common bug in all of the versions (smells like an uninitialized variable in
gcc since it's so random). Well we have to watch it for now....

BTW, how are curves?


Michal

On Fri, Mar 13, 2015 at 4:53 AM, Konstantin Sharlaimov <
notifications@github.com> wrote:

> I've noticed that sometimes gcc-arm-none-eabi-4.9 provides buggy code for
> STM32F103 processor. I don't know exact conditions to reproduce the bug,
> but currently I stick with gcc 4.8 toolchain - provides working code for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/art103/ar-t6/issues/5#issuecomment-78937345>.
>



-- 
Michal, Iza, Kai & Nell

**Comment by michkrom** [comment]
Conclusions -
- the fw can be flashed with stm32flash utility
- a custom cable or USB data cable to CT6 can be used
- the flash mode can be entered programmatically from both original fw and custom one
- the tx can be soft-bricked if flashing gets interrupted (recovery with SWD connection)
- the 128kB of flash is usable albeit it may be out of spec (datasheet reports only 64k for this part)

Flashing description:
http://minkbot.blogspot.com/2015/03/fs-t6-firmware-upgrade.html
